nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    "^/api/":
      allow_origin: ["*"]
      forced_allow_origin_value: "*"
      allow_headers: ["Content-Type", "Authorization", "X-Requested-With", "X-App-Name"]
      allow_methods: ["GET"]
      max_age: 3600
    "^/":
      origin_regex: true
      allow_origin: ["%env(string:CORS_ALLOW_ORIGIN)%"]
      allow_headers: ["X-Custom-Auth"]
      allow_methods: ["POST", "PUT", "GET", "DELETE"]
      max_age: 3600
      hosts: ['^api\.']
